### PR TITLE
[WIP] Windows color

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by alexispurslane** [comment]
Sorry, I'm switching this to GoLang, so any C stuff your do will have to go (no pun intended).

**Comment by mattn** [comment]
I don't mind. I love Go too. :)

**Comment by alexispurslane** [comment]
BTW I'm learning Go as i go so if anyone wants to recommend some good documentation material, please do. I picked go becouse it is compiled, seems like a nice language, and is well supported.

**Comment by mattn** [comment]
okay :)

**Pull request closed without merging**
